Feature/school 17
Dumaem/DumaemSchool pull request #18
Opened 2023-10-13 17:00 UTC by riazonbin

2023-10-13 20:07 UTC, WingiM requested changes

2023-10-13 20:07 UTC, WingiM commented on DumaemSchool.BlazorWeb/Data/TimeRange.cs
> +    public class TimeRange
удалить

2023-10-13 20:07 UTC, WingiM commented on DumaemSchool.BlazorWeb/Pages/SectionPage.razor
> +    private HashSet<TeacherDto>? _teachersToSelect;
а зачем нужна эта переменная? и без нее можно обойтись
и почему хешсет

2023-10-13 20:07 UTC, WingiM commented on DumaemSchool.BlazorWeb/Pages/SectionPage.razor
> +                Filters = new[] { new FilterDefinition { Value = value, Operand = FilterOperand.Contains, FieldName = "Name" } }
Вместо фильтров в виде строки лучше брать nameof(TeacherDto.Name), чтобы при изменении названий полей ничего не ломалось

2023-10-13 20:07 UTC, WingiM commented on DumaemSchool.BlazorWeb/Pages/SectionPage.razor
> +            Snackbar.Configuration.PositionClass = Defaults.Classes.Position.BottomLeft;
этот конфиг нельзя сделать как-то глобально? чтобы не каждый раз вот так

2023-10-13 20:07 UTC, WingiM commented on DumaemSchool.BlazorWeb/Program.cs
> +//Add localisation
localiZation

2023-10-13 20:07 UTC, WingiM commented on DumaemSchool.BlazorWeb/Shared/ActivityAndAttendance.razor
> +    private Dictionary<LessonActivityMark, string> MarksOnRussianLanguage = new Dictionary<LessonActivityMark, string>()
название неправильное
это приватный член, должно быть _marksOnRussianLanguage
а вообще сделай это статическим и подними в самый верх. и не нужно название менять

2023-10-13 20:07 UTC, WingiM commented on DumaemSchool.BlazorWeb/Shared/ActivityAndAttendance.razor
> +    private Dictionary<bool, string> AttendanceOnRussianLanguage = new Dictionary<bool, string>()
static

2023-10-13 20:07 UTC, WingiM commented on DumaemSchool.BlazorWeb/Shared/ActivityAndAttendance.razor
> +    protected override Task OnAfterRenderAsync(bool firstRender)
мусор

2023-10-13 20:07 UTC, WingiM commented on DumaemSchool.BlazorWeb/Shared/ActivityAndAttendance.razor
> +        else
елз не нужен, лишняя вложенность получается

2023-10-13 20:07 UTC, WingiM commented on DumaemSchool.BlazorWeb/Shared/Schedule.razor
> +
один ентер удалить

2023-10-13 20:07 UTC, WingiM commented on DumaemSchool.BlazorWeb/Shared/Schedule.razor
> +            filters.Add(new FilterDefinition { FieldName = nameof(SectionSchedule.SectionId), Value = SectionId, Operand = FilterOperand.Equal });
а здесь неймоф используешь)

2023-10-13 20:07 UTC, WingiM commented on DumaemSchool.BlazorWeb/Shared/Students.razor
> +    private HashSet<StudentToAddToSection>? _studentsToAdd;
опять ненужная переменная
и опять почему хешсет

2023-10-13 20:07 UTC, WingiM commented on DumaemSchool.BlazorWeb/Shared/Students.razor
> +                        { new FilterDefinition { Value = SectionId!.Value, Operand = FilterOperand.Equal, FieldName = "SectionId" },
почему SectionId nullable? не вижу где бы он был налл, зато везде восклицательные знаки

2023-10-13 20:07 UTC, WingiM commented on DumaemSchool.BlazorWeb/Shared/Students.razor
> +
убрать 1 ентер

2023-10-13 20:07 UTC, WingiM commented on DumaemSchool.BlazorWeb/Shared/Students.razor
> +
убрать 1 ентер

2023-10-13 20:07 UTC, WingiM commented on DumaemSchool.Core/Commands/Section/CheckStudentAvailabilityToSectionCommand.cs
> +    {
фигурные скобки убрать

2023-10-13 20:07 UTC, WingiM commented on DumaemSchool.Database/Repositories/Impl/TeacherRepository.cs
> +    public async Task<bool> AddTeacherToSection(int teacherId, int sectionId, int oldTeacherId)
если отправить неверный oldTeacherId, можно саботировать работу метода
айди старого учителя не нужен, потому что он определяется актуальной записью для кружка, она всегда одна

2023-10-13 20:07 UTC, WingiM commented on DumaemSchool.Database/Repositories/Impl/TeacherRepository.cs
> +        var oldSectionTeacherRecord = await _context.SectionTeachers.FirstOrDefaultAsync(x => x.IsActual == true && x.Teacher.Id == oldTeacherId
и тогда здесь достаточно условия x.IsActual == true && x.SectionId == sectionId

2023-10-13 20:07 UTC, WingiM commented on DumaemSchool.BlazorWeb/Pages/SectionPage.razor
> +    private TeacherDto? _oldTeacher;
и получается для _oldTeacher достаточно хранить айди и сравнивать только его

2023-10-14 04:25 UTC, riazonbin commented on DumaemSchool.BlazorWeb/Pages/SectionPage.razor
> +    private HashSet<TeacherDto>? _teachersToSelect;
для того, чтобы по старому преподавателю isActual ставить false.
хэшсет, да не знаю, можно было и лист. Это существенную роль тут играет?

2023-10-14 04:27 UTC, riazonbin commented on DumaemSchool.BlazorWeb/Pages/SectionPage.razor
> +    private HashSet<TeacherDto>? _teachersToSelect;
+ нужно еще отслеживать, активировать ли кнопку "Сохранить"

2023-10-14 04:45 UTC, riazonbin commented on DumaemSchool.BlazorWeb/Pages/SectionPage.razor
> +            Snackbar.Configuration.PositionClass = Defaults.Classes.Position.BottomLeft;
не знаю даже

2023-10-14 04:46 UTC, riazonbin commented on DumaemSchool.BlazorWeb/Program.cs
> +//Add localisation
![image](https://github.com/Dumaem/DumaemSchool/assets/84237219/f7e94415-af52-46d1-adbd-a2884c34ebcb)

2023-10-14 04:55 UTC, riazonbin commented on DumaemSchool.Database/Repositories/Impl/TeacherRepository.cs
> +    public async Task<bool> AddTeacherToSection(int teacherId, int sectionId, int oldTeacherId)
теперь понял, спасибо

2023-10-14 05:09 UTC, riazonbin commented on DumaemSchool.BlazorWeb/Shared/Students.razor
> +    private HashSet<StudentToAddToSection>? _studentsToAdd;
а какой тип корректнее ставить то? лист?

2023-10-14 05:43 UTC, riazonbin commented on DumaemSchool.BlazorWeb/Shared/Students.razor
> +    private HashSet<StudentToAddToSection>? _studentsToAdd;
и почему это ненужная? это же новый студент, который выбирается, я его храню через bind

2023-10-14 06:33 UTC, WingiM approved these changes

2023-10-14 06:43 UTC, Flictivity commented on DumaemSchool.BlazorWeb/Pages/SectionPage.razor
> +            Snackbar.Configuration.PositionClass = Defaults.Classes.Position.BottomLeft;
можно
![image](https://github.com/Dumaem/DumaemSchool/assets/85502952/420aeb5e-4753-49e0-b35b-b86322fcb8d9)

2023-10-14 06:54 UTC, merged