Feature/school 8
Dumaem/DumaemSchool pull request #5
Opened 2023-10-03 07:14 UTC by Flictivity

2023-10-03 07:47 UTC, WingiM requested changes

2023-10-03 07:47 UTC, WingiM commented on DumaemSchool.BlazorWeb/DumaemSchool.BlazorWeb.csproj
>      <Nullable>enable</Nullable>
ban

2023-10-03 07:49 UTC, WingiM requested changes

2023-10-03 07:49 UTC, WingiM commented on DumaemSchool.BlazorWeb/Shared/AuthorizationComponents/EmailLoginForm.razor
> +    private TimeSpan _counter = _countdownDurationSeconds;
Таймер не вытащил

2023-10-03 16:31 UTC, Flictivity commented on DumaemSchool.BlazorWeb/Shared/AuthorizationComponents/EmailLoginForm.razor
> +    private TimeSpan _counter = _countdownDurationSeconds;
Вынес

2023-10-03 16:31 UTC, Flictivity commented on DumaemSchool.BlazorWeb/DumaemSchool.BlazorWeb.csproj
>      <Nullable>enable</Nullable>
За что так, это все VisualStudio виновата((

2023-10-03 16:46 UTC, WingiM commented on DumaemSchool.BlazorWeb/Shared/AuthorizationComponents/EmailLoginForm.razor
> +        Timer.Dispose();
а его точно нужно диспозить тут? мб диспоз таймера вытащить в логин?

2023-10-04 13:53 UTC, WingiM approved these changes

2023-10-04 13:55 UTC, merged